id: ID929E40E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T00:36:06+00:00'
last_modified: '2022-06-10T09:24:22.106972+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4265
  title: སངས་རྒྱས་བཀྲ་ཤིས་སམ་སྲོག་བདག་རྡོ་རྗེ་དཔའ་བོ་རྩལ་གྱི་བྱུང་བ་བརྗོད་པའི་ས་བོན་ཉེར་མཁོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    5FFD:
      image_group_id: I1KG4991
      title: Volume 1 of sangs rgyas bkra shis sam srog bdag rdo rje dpa' bo rtsal
        gyi byung ba brjod pa'i sa bon nyer mkho
      total_pages: 50
      order: 1
      base_file: 5FFD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
